---
title: "Assignment_3_3402_amana4"
author: "Aman Arora"
date: "3/7/2021"
output:
  html_document: 
    theme: readable
    toc: yes  
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Function Prepartion 

```{r}
lo.lev <- function(x1, sp){
  # x1: n-by-1 feature vector
  # sp: a numerical value for "span"
  ##############################################
  # YOUR CODE: Compute the diagonal entries of the 
  #            smoother matrix S and 
  #            store it in a vector "lev"
  # Tip: check how we compute the smoother matrix
  #      for smoothing spline models
  ##############################################
  
  n = length(x1);
  lev = rep(0, n)
  A = matrix(0,n,n)
  
  for(i in 1:n)
  {
    y  = rep(0,n); y[i] = 1;
    yi = fitted(loess(y ~ x1, span = sp , control = loess.control(surface = "direct")))
    A[,i] = yi

  }
  lev = diag(A)  
  return(lev)
}
```


```{r}
onestep_CV <- function(x1, y1, sp){
  
  ##############################################
  #  YOUR CODE: 
  #  1) Fit a loess model y1 ~ x1 with span = sp, and extract 
  #     the corresponding residual vector
  #  2) Call lo.lev to obtain the diagonal entries of S
  #  3) Compute LOO-CV and GCV using formula from lecture notes
  #    [lec_W5_NonlinearRegression.pdf] page 33. 
  ##############################################
  
  #1 Fit a loess model y1 ~ x1 with span = sp, and extract the corresponding residual vector
  
  res = loess(y1 ~ x1, span = sp,control = loess.control(surface = "direct"))$res

  #2 Call lo.lev to obtain the diagonal entries of S
  diag_s = lo.lev(x1,sp) 
  
  #  3) Compute LOO-CV and GCV using formula from lecture notes
  #    [lec_W5_NonlinearRegression.pdf] page 33. 
  
   n = NROW(res)  
   mean_trace = mean(diag_s)
   
   cv = sum( (res/(1- diag_s))^2)/n
   gcv = sum( (res/(1- mean_trace))^2)/n
  
  return(list(cv = cv, gcv = gcv))
}
```


```{r}
myCV <- function(x1, y1, span){
  # x1: feature vector of length n
  # y1: response vector of length n
  # span: a sequence of values for "span"
  
  m = length(span)
  cv = rep(0, m)
  gcv = rep(0, m)
  
  for(i in 1:m){
    tmp = onestep_CV(x1, y1, span[i])
    cv[i] = tmp$cv
    gcv[i] = tmp$gcv
  }
  return(list(cv = cv, gcv = gcv))
}
```

# Testing the functions

```{r}
mydata = read.csv(file = "Coding3_Data.csv")

```

```{r}
dim(mydata)
plot(mydata$x, mydata$y, xlab="", ylab="")

```

```{r}
span1 = seq(from = 0.2, by = 0.05, length = 15 )
cv.out = myCV(mydata$x, mydata$y, span1)

```


```{r}
myout = data.frame(CV = cv.out$cv, 
                   GCV = cv.out$gcv, 
                   span = span1)
myout
```


```{r}
myout$span[myout$CV == min(myout$CV)]

```

# Plot the curve

```{r}
spangcv.min = 0.5
plot(mydata$x, mydata$y, xlab="", ylab="", col="gray");
fx = 1:50/50;
fy = sin(12*(fx+0.2))/(fx+0.2)
lines(fx, fy, col=8, lwd=2);

f = loess(y ~ x, mydata, span = spangcv.min)
lines(fx, predict(f, data.frame(x = fx), surface = "direct"), 
      lty=2, lwd=2, col="blue")
```


