---
title: "Final Project"
author: "Team: Summer Proj"
Date: 13th July, 2020
output:
  html_document: 
    theme: readable
    toc: yes  
  pdf_document: default
urlcolor: cyan
---

***

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
options(scipen = 1, digits = 4, width = 80)
library(knitr)
opts_chunk$set(cache = TRUE, autodep = TRUE)
```

# Boxoffice hit or miss

## Data Analysis
```{r}
#Diagnostics for linear regression
diagnostics <- function(model, pcol = "grey", lcol = "dodgerblue", alpha = 0.05, plotit = TRUE, testit = TRUE)
{
  result = list(p_val = 0, decision = "NA")
  if(plotit == TRUE)
  {
    par(mfrow = c(1,2))
    plot(fitted(model), resid(model), xlab = "Fitted", ylab = "Residuals", col = pcol )
    abline(h =0, col = lcol)

    qqnorm(resid(model),col = pcol )
    qqline(resid(model),col = lcol)
    
  }
  
  if(testit == TRUE)
  {
    stest = shapiro.test(resid(model))
    result[["p_val"]] =  stest$p.value
    result[["decision"]] = ifelse(stest$p.value >alpha,"Fail to Reject", "Reject")
    return (result)
  }
  
}
```



```{r}
#Read  in the data set
df = read.csv("tmdb_5000_movies.csv")

#Select the relavent columns 
col_sel = c("original_title", "budget", "revenue", "popularity", "vote_average","vote_count","original_language")
df1 = df[,col_sel]

#Find rows with invalid values
df1[df1$budget == 0, "budget" ] = NA
df1[df1$revenue == 0, "revenue" ] = NA
df1[df1$popularity == 0, "popularity" ] = NA
df1[df1$vote_count == 0, "vote_count" ] = NA
df1= df1[df$original_language == "en",]
#remove invalid rows
df1 =  na.omit(df1)

dim(df1)
dim(df)
```


```{r}
#Fit the model and print summary
boxoffice_model_1 = lm(revenue ~  budget*popularity*vote_average*vote_count, df1)
summary(boxoffice_model_1)

#Run diagnostics on the model
diagnostics(boxoffice_model_1, alpha = 0.1)
```
```{r}
#Find indices of rows that do not have influential observations
retain_idx =  cooks.distance(boxoffice_model_1) < 4/length(cooks.distance(boxoffice_model_1))
boxoffice_model_1 = lm(revenue ~  budget*popularity*vote_average*vote_count, df1[retain_idx,])

summary(boxoffice_model_1)

#Run diagnostics on the model
diagnostics(boxoffice_model_1, alpha = 0.1)
```


```{r}
unique(df$original_language)
```

```


