---
title: "Assignment_2_3402_amana4.Rmd"
author: "Aman Arora (amana4@illinois.edu)"
date: "2/22/2021"
output:
  html_document: 
    theme: readable
    toc: yes  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
myData = read.csv("Coding2_myData.csv")
X = as.matrix(myData[, -14])
y = myData$Y
dim(X)
```

## One variable  Lasso function 

```{r}
one_var_lasso = function(r, x, lam) {
    xx = sum(x^2)
    xr = sum(r * x)
    b = (abs(xr) - lam/2)/xx
    b = sign(xr) * ifelse(b > 0, b, 0)
    return(b)
}
```

## Lasso function 

```{r}
MyLasso = function(X, y, lam.seq, maxit = 500) {
    
    # X: n-by-p design matrix without the intercept 
    # y: n-by-1 response vector 
    # lam.seq: sequence of lambda values 
    # maxit: number of updates for each lambda 
    # Center/Scale X
    # Center y
  
    n = length(y)
    p = dim(X)[2]
    nlam = length(lam.seq)
    Xs = as.matrix(X)
   
    #Center and scale to unit variance and zero mean for each col. 
    y.mean = mean(y)
    
    for(i in 1:p)
    {
      current_col = X[,i]
      #glmnet uses n instead of n-1
      Xs[,i] = (current_col - mean(current_col))/(sd(current_col) * sqrt((n-1)/n))
    }
    
    
    # Initilize coef vector b and residual vector r
    b = rep(0, p)
    r = y
    B = matrix(nrow = nlam, ncol = p + 1)
    
    # Triple nested loop
    for (m in 1:nlam) {
        lam = 2 * n * lam.seq[m]
        for (step in 1:maxit) {
            for (j in 1:p) {
                r = r + (Xs[, j] * b[j])
                b[j] = one_var_lasso(r, Xs[, j], lam)
                r = r - Xs[, j] * b[j]
            }
        }
        B[m, ] = c(0, b)
    }

    #de-Scale and de-center the coeff.
    
    for(i in 1:nrow(B))
    {
      delta = 0
      #start from 2nd col. for B, X does not have intercept hence j-1   
      for(j in 2:(p+1))
      {
        B[i,j] = B[i,j]/ (sd(X[,j-1])*sqrt((n-1)/n))
        delta = delta + mean(X[,j-1])*B[i,j]
        
      }
      
      B[i, 1] = y.mean - delta
      
    }
    
    return(t(B))
    
    
}
```

## Main function  

```{r}

lam.seq = exp(seq(-1, -8, length.out = 80))
myout = MyLasso(X, y, lam.seq, maxit = 100) 
rownames(myout) = c("Intercept", colnames(X)) 
dim(myout)
```

```{r}

myout[1,]

```

```{r}
x.index = log(lam.seq)
beta = myout[-1, ]  # beta is a 13-by-80 matrix
matplot(x.index, t(beta),
        xlim = c(min(x.index), max(x.index)),
        lty = 1,
        xlab = "Log Lambda",
        ylab = "Coefficients",
        type="l", 
        lwd = 1)
```

## Accuracy Check

```{r}
library(glmnet)
lasso.fit = glmnet(X, y, alpha = 1, lambda = lam.seq)
# coef(lasso.fit)
write.csv(as.matrix(coef(lasso.fit)), file = "Coding2_lasso_coefs.csv", 
          row.names = FALSE)
```

```{r}
max(abs(coef(lasso.fit) - myout))

```

```{r}
plot(lasso.fit, xvar = "lambda")
```

